services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: storytime
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - storytime_postgres_data:/var/lib/postgresql/data

volumes:
  storytime_postgres_data:

